language: node_js
node_js:
  - 0.10

services:
  - mongodb
  - redis-server

before_install: 
  - npm install -g grunt-cli
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install
  - node app.js > /dev/null &
  - sleep 10 # give server time to start

script:
  - grunt test